### ISSUE TITLE
Multiple errors processing MD files

### ISSUE THREAD

**Issue by mbdiener** [karloskalcium/md2enex#14]
Hi,
I installed and have been trying to use this program to convert a number of .md files exported from Notion to an .enex file. I have been receiving the following errors for each file it processes. I am also attaching one of the .md files.

WARNING:root:Parsing error <class 'lxml.etree.XMLSyntaxError'> occurred with file d:\EVImp\Cauliflower Shawarma With Spicy Tahini Recipe (wit 4f36573b95bb439ba3a3a609e4207315.md
WARNING:root:No declaration for attribute type of element input, line 3, column 1219 (<string>, line 3)
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for attribute type of element inputat line: 3
ERROR:root:No declaration for attribute disabled of element inputat line: 3
ERROR:root:No declaration for element inputat line: 3
ERROR:root:Element input is not declared in li list of possible childrenat line: 3
ERROR:root:No declaration for element asideat line: 3
ERROR:root:No declaration for attribute aria-hidden of element figcaptionat line: 3
ERROR:root:No declaration for element figcaptionat line: 3
ERROR:root:No declaration for element figureat line: 3
ERROR:root:No declaration for attribute aria-hidden of element figcaptionat line: 3
ERROR:root:No declaration for element figcaptionat line: 3
ERROR:root:No declaration for element figureat line: 3
ERROR:root:Element aside is not declared in en-note list of possible childrenat line: 3
ERROR:root:Element figure is not declared in en-note list of possible childrenat line: 3
ERROR:root:Element figure is not declared in en-note list of possible childrenat line: 3
[Cauliflower Shawarma With Spicy Tahini Recipe (wit 4f36573b95bb439ba3a3a609e4207315.md](https://github.com/user-attachments/files/16629237/Cauliflower.Shawarma.With.Spicy.Tahini.Recipe.wit.4f36573b95bb439ba3a3a609e4207315.md)

Can you advise if I am doing something wrong or if there is an issue with the files?

Thanks

**Comment by karloskalcium** [comment]
Hi thanks @mbdiener for the report and attached file, the code wasn't handling task lists properly. I've now added some support for that but they will show up as lists (not task lists, as that would require creating a whole separate section of the export I believe). If you download version 0.3 it should work.
