### ISSUE TITLE
no DTD found

### ISSUE THREAD

**Issue by HappyMiMiMi** [karloskalcium/md2enex#5]
WARNING:root:Validation failed: no DTD found !, line 3, column 9 (<string>, line 3)
Please tell me how to use DTD with this project.

**Comment by karloskalcium** [comment]
@HappyMiMiMi can you describe more what you are running when it gives you this error?

**Comment by hlbmallo** [comment]
I've been having this issue too. I've cloned the repository, created and am running a virtual Python env, installed pandoc and lxml, but when I execute the following...

`python3 .\md2enex.py -d C:\Dev\Clone\md2enex -o hello.enex`

The result for all of my .md files in the directory is (example below)...

```(my-venv) C:\Dev\Clone\md2enex>python3 .\md2enex.py -d C:\Room\ -o hello.enex
WARNING:root:Parsing error <class 'lxml.etree.XMLSyntaxError'> occurred with file choles.md
WARNING:root:Validation failed: no DTD found !, line 3, column 9 (<string>, line 3)
```

Any advice on how to get round this would be really appreciated.

Thanks for the class tool by the way!

**Comment by karloskalcium** [comment]
Thanks for the report. Could you try to run it against the test file and see if you get the same error?
`python3 .\md2enex.py -d test/test1/`

Also which OS are you using?

**Comment by hlbmallo** [comment]
That's it, it's working now with that line commented out - in both the test code and my code - thanks very much for your advice! 

Thanks again for the tool. If I had more knowledge of python I'd love to work with the code to get images exported to .enex too... maybe some day though.

Cheers man!

**Comment by karloskalcium** [comment]
should be closed in https://github.com/karloskalcium/md2enex/releases/tag/0.2.0
